# Don't use this file alone, please retrieve https://github.com/convertigo/docker/archive/refs/heads/compose.tar.gz
# You can retrieve it in your current directory with:
# curl -sL https://github.com/convertigo/docker/archive/refs/heads/compose.tar.gz | tar xvz --strip-components=1
# Edit the .env file then start with "docker compose up -d" and end with "docker compose down"

name: convertigo

services:
  convertigo_0:
    hostname: convertigo_0
    image: "${CONVERTIGO_IMAGE}"
    restart: ${RESTART_POLICY}
    deploy:
      replicas: 1
    ports:
     - "28080:28080"
     - "28443:28443"
    volumes:
     - ./data/workspace:/workspace
     - ./init/certs:/ssl:ro
    environment:
     - JAVA_OPTS=
       -Dconvertigo.engine.log4j.appender.CemsAppender.File=/workspace/logs/0/engine.log
       -Dconvertigo.engine.billing.enabled=true
       -Dconvertigo.engine.billing.persistence.jdbc.username=${CONVERTIGO_BILLING_USER}
       -Dconvertigo.engine.billing.persistence.jdbc.password=${CONVERTIGO_BILLING_PASSWORD}
       -Dconvertigo.engine.billing.persistence.jdbc.url=jdbc:postgresql://timescaledb/${CONVERTIGO_BILLING_DB}
       -Dconvertigo.engine.billing.persistence.jdbc.driver=org.postgresql.Driver
       -Dconvertigo.engine.billing.persistence.dialect=org.hibernate.dialect.PostgreSQLDialect
       -Dconvertigo.engine.fullsync.couch.username=${CONVERTIGO_FULLSYNC_USER}
       -Dconvertigo.engine.fullsync.couch.password=${CONVERTIGO_FULLSYNC_PASSWORD}
     - CONVERTIGO_ADMIN_USER
     - CONVERTIGO_ADMIN_PASSWORD
     - LOG_STDOUT=${CONVERTIGO_LOG_STDOUT}
     - LOG_FILE=${CONVERTIGO_LOG_FILE}
     - JXMX=${CONVERTIGO_JXMX}
     - COOKIE_PATH=${CONVERTIGO_COOKIE_PATH}
     - COOKIE_SECURE=${CONVERTIGO_COOKIE_SECURE}
     - COOKIE_SAMESITE=${CONVERTIGO_COOKIE_SAMESITE}
     - SESSION_TIMEOUT=${CONVERTIGO_SESSION_TIMEOUT}
     - DISABLE_SUDO=${CONVERTIGO_DISABLE_SUDO}
     - BASEROW_PUBLIC_URL
    command: >
      /bin/sh -c "chown convertigo:convertigo /workspace
        /docker-entrypoint.sh convertigo"

  convertigo_1:
    hostname: convertigo_1
    image: "${CONVERTIGO_IMAGE}"
    restart: ${RESTART_POLICY}
    deploy:
      replicas: ${CONVERTIGO_MULTI_ENABLE}
    ports:
     - "28081:28080"
     - "28444:28443"
    volumes:
     - ./data/workspace:/workspace
    depends_on:
      - convertigo_0
    environment:
     - JAVA_OPTS=
       -Dconvertigo.engine.log4j.appender.CemsAppender.File=/workspace/logs/1/engine.log
       -Dconvertigo.engine.billing.enabled=true
       -Dconvertigo.engine.billing.persistence.jdbc.username=${CONVERTIGO_BILLING_USER}
       -Dconvertigo.engine.billing.persistence.jdbc.password=${CONVERTIGO_BILLING_PASSWORD}
       -Dconvertigo.engine.billing.persistence.jdbc.url=jdbc:postgresql://timescaledb/${CONVERTIGO_BILLING_DB}
       -Dconvertigo.engine.billing.persistence.jdbc.driver=org.postgresql.Driver
       -Dconvertigo.engine.billing.persistence.dialect=org.hibernate.dialect.PostgreSQLDialect
       -Dconvertigo.engine.fullsync.couch.username=${CONVERTIGO_FULLSYNC_USER}
       -Dconvertigo.engine.fullsync.couch.password=${CONVERTIGO_FULLSYNC_PASSWORD}
     - CONVERTIGO_ADMIN_USER
     - CONVERTIGO_ADMIN_PASSWORD
     - LOG_STDOUT=${CONVERTIGO_LOG_STDOUT}
     - LOG_FILE=${CONVERTIGO_LOG_FILE}
     - JXMX=${CONVERTIGO_JXMX}
     - COOKIE_PATH=${CONVERTIGO_COOKIE_PATH}
     - COOKIE_SECURE=${CONVERTIGO_COOKIE_SECURE}
     - COOKIE_SAMESITE=${CONVERTIGO_COOKIE_SAMESITE}
     - SESSION_TIMEOUT=${CONVERTIGO_SESSION_TIMEOUT}
     - DISABLE_SUDO=${CONVERTIGO_DISABLE_SUDO}
     - BASEROW_PUBLIC_URL

  couchdb:
    image: "${COUCHDB_IMAGE}"
    restart: ${RESTART_POLICY}
    deploy:
      replicas: ${COUCHDB_ENABLE}
    ports:
     - "28090:5984"
    environment:
     - COUCHDB_USER=${CONVERTIGO_FULLSYNC_USER}
     - COUCHDB_PASSWORD=${CONVERTIGO_FULLSYNC_PASSWORD}
    volumes:
     - ./data/fullsync:/opt/couchdb/data
    command: >
      /bin/sh -c "echo '[couchdb]
        single_node=true' > /opt/couchdb/etc/local.d/setup.ini
        /docker-entrypoint.sh couchdb"

  timescaledb:
    image: "${TIMESCALEDB_IMAGE}"
    restart: ${RESTART_POLICY}
    deploy:
      replicas: ${TIMESCALEDB_ENABLE}
    ports:
     - "28092:5432"
    volumes:
     - ./data/timescaledb:/var/lib/postgresql/data
     - ./init/timescaledb:/docker-entrypoint-initdb.d
    environment:
     - POSTGRES_PASSWORD=${TIMESCALEDB_PASSWORD}
     - POSTGRES_USER=${TIMESCALEDB_USER}
     - BILLING_DB=${CONVERTIGO_BILLING_DB}
     - BILLING_PASSWORD=${CONVERTIGO_BILLING_PASSWORD}
     - BILLING_USER=${CONVERTIGO_BILLING_USER}
     - BASEROW_DB
     - BASEROW_USER
     - BASEROW_PASSWORD
    command: >
      /bin/sh -c "
        chmod +x /docker-entrypoint-initdb.d/*.sh
        docker-entrypoint.sh postgres"

  httpd:
    image: "${HTTPD_IMAGE}"
    restart: ${RESTART_POLICY}
    deploy:
      replicas: ${HTTPD_ENABLE}
    ports:
      - "${HTTPD_HTTP_PORT}:80"
      - "${HTTPD_HTTPS_PORT}:443"
    volumes:
      - "./init/certs:/usr/local/apache2/conf/certs:ro"
      - "./init/httpd:/usr/local/apache2/custom:ro"
    depends_on:
      - convertigo_0
    environment:
     - PUBLIC_HOSTNAME
     - HTTPD_HTTPS_PORT
     - HTTPD_HTTPS_REDIRECT
     - HTTPD_ROOT_URL
     - CONVERTIGO_MULTI_ENABLE
    command: >
      /bin/sh -c "
        if ! grep -q 'Include /usr/local/apache2/custom/convertigo.conf' /usr/local/apache2/conf/httpd.conf; then
          echo 'Include /usr/local/apache2/custom/convertigo.conf' >> /usr/local/apache2/conf/httpd.conf;
        fi
        httpd-foreground"

  baserow:
    image: "${BASEROW_IMAGE}"
    restart: ${RESTART_POLICY}
    deploy:
      replicas: ${BASEROW_ENABLE}
    depends_on:
      - timescaledb
    ports:
      - "28094:80"
    volumes:
      - "./data/baserow:/baserow/data"
    entrypoint: >
      /bin/sh -c "
        sed -i -e s,127.0.0.1,0.0.0.0, /baserow/supervisor/default_baserow_env.sh
        /baserow.sh start"
    environment:
     - BASEROW_PUBLIC_URL
     - BASEROW_EXTRA_ALLOWED_HOSTS
     - DATABASE_HOST=timescaledb
     - DATABASE_PORT=5432
     - DATABASE_NAME=${BASEROW_DB}
     - DATABASE_USER=${BASEROW_USER}
     - DATABASE_PASSWORD=${BASEROW_PASSWORD}
