#!/bin/bash
set -e

if [[ -z "$BASEROW_USER" || -z "$BASEROW_PASSWORD" || -z "$BASEROW_DB" ]]; then
  echo "Missing variables BASEROW_USER, BASEROW_PASSWORD, and BASEROW_DB."
else
  psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER "$BASEROW_USER" WITH PASSWORD '$BASEROW_PASSWORD';
    CREATE DATABASE "$BASEROW_DB" OWNER "$BASEROW_USER";
    GRANT ALL PRIVILEGES ON DATABASE "$BASEROW_DB" TO "$BASEROW_USER";
EOSQL
fi
