#!/bin/bash

VERSION=$(sed -n 's/ARG CONVERTIGO_VERSION=\(.*\)/\1/p' Dockerfile)

if [ "$SOURCE_BRANCH" = "master" ]; then
    docker tag $IMAGE_NAME ${IMAGE_NAME}-$VERSION
    docker push ${IMAGE_NAME}-$VERSION
fi

if [ "$DOCKER_TAG" = "mbaas" ]; then    
    docker tag $IMAGE_NAME $DOCKER_REPO:latest
    docker push $DOCKER_REPO:latest
fi

if [[ "$DOCKER_TAG" = mbaas* ]]; then
    docker tag $IMAGE_NAME $DOCKER_REPO:$VERSION
    docker push $DOCKER_REPO:$VERSION
fi
