#!/bin/bash

## parse environment variables
. versions.sh

## mbaas is the default mode, declare tag without the mode

if [ "$CONVERTIGO_MODE" = "mbaas" ]; then
    echo_and_run docker tag $DOCKER_REPO:$CONVERTIGO_MODE-$CONVERTIGO_VERSION $DOCKER_REPO:$CONVERTIGO_VERSION
    echo_and_run docker push $DOCKER_REPO:$CONVERTIGO_VERSION
fi


## if latest request, also tag without version

if [ "$CONVERTIGO_LATEST" = "yes" ]; then
    echo_and_run docker tag $DOCKER_REPO:$CONVERTIGO_MODE-$CONVERTIGO_VERSION $DOCKER_REPO:$CONVERTIGO_MODE
    echo_and_run docker push $DOCKER_REPO:$CONVERTIGO_MODE
    
    if [ "$CONVERTIGO_MODE" = "mbaas" ]; then
        echo_and_run docker tag $DOCKER_REPO:$CONVERTIGO_MODE-$CONVERTIGO_VERSION $DOCKER_REPO:latest
        echo_and_run docker push $DOCKER_REPO:latest
    fi
fi
